"""links tab partial index

Revision ID: 4471a6d661d3
Revises: bdbf829f823f
Create Date: 2026-07-25 18:20:11.402117

Hand-written (not autogenerated): the models do not describe this index, because
its predicate is the Links tab's own scan filter rather than a schema property.

Why not the existing search_tsv GIN index: to_tsvector('simple', ...) discards
the `protocol` token, so 'https://example.com/x' indexes as
{example.com, example.com/x, /x} with no 'http' lexeme to query for, and the
per-URL host lexemes cannot be enumerated in advance. Full-text search cannot
answer "does this message contain a link"; a partial index on the same ILIKE
predicate can.

Trade-off: every message write now evaluates a fixed substring test to decide
index membership, and the predicate must stay identical to the query in
app/api/media.py (_LINK_PATTERN) or Postgres silently stops using the index.
In exchange the Links tab reads only link-bearing rows instead of the
conversation's entire history.
"""

from alembic import op

revision = "4471a6d661d3"
down_revision = "bdbf829f823f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """CREATE INDEX ix_messages_links ON messages (conversation_id, created_at DESC)
           WHERE content ILIKE '%http%'"""
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_messages_links")
