"""links tab partial index

Revision ID: 4471a6d661d3
Revises: bdbf829f823f
Create Date: 2026-07-25 18:20:11.402117

Hand-written (not autogenerated): the models do not describe this index, because
its predicate is the Links tab's own scan filter rather than a schema property.

Why not the existing search_tsv GIN index: to_tsvector('simple', ...) discards
the `protocol` token, so 'https://example.com/x' indexes as
{example.com, example.com/x, /x} with no 'http' lexeme to query for, and the
per-URL host lexemes cannot be enumerated in advance. Full-text search cannot
answer "does this message contain a link"; a partial index on the same ILIKE
predicate can.

Trade-off: every message write now evaluates a fixed substring test to decide
index membership, and the predicate must stay identical to the query in
app/api/media.py (_LINK_PATTERN) or Postgres silently stops using the index.
In exchange the Links tab reads only link-bearing rows instead of the
conversation's entire history.
"""

from alembic import op

revision = "4471a6d661d3"
down_revision = "bdbf829f823f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # CONCURRENTLY, like b7e21c4a9d33, c5d81e37a204 and a4f81c6b2e07. This one was
    # not, and messages is the table it least should have been: a row per message
    # sent. A plain CREATE INDEX holds SHARE for a full heap scan, which conflicts
    # with the ROW EXCLUSIVE every INSERT takes, so the build blocks sends for as
    # long as it runs — and production boots with
    # `alembic upgrade head && python -m app.seed && uvicorn ...`
    # (infra/docker-compose.prod.yml), so on a large table the API does not merely
    # queue writes behind this, it never finishes starting.
    #
    # Nothing to trade away here: this migration creates the index and does
    # nothing else, so leaving the transaction costs it no atomicity. The DROP
    # first is what makes the retry safe instead — a cancelled concurrent build
    # leaves an INVALID index of the same name, and this revision is not stamped
    # until upgrade() returns, so the retry re-enters here and must clear it. The
    # index is not unique, so an INVALID one enforces nothing; it is simply never
    # used by the planner, which would leave the Links tab scanning whole
    # conversations while the migration reported success.
    with op.get_context().autocommit_block():
        op.execute("DROP INDEX CONCURRENTLY IF EXISTS ix_messages_links")
        op.execute(
            """CREATE INDEX CONCURRENTLY ix_messages_links
               ON messages (conversation_id, created_at DESC)
               WHERE content ILIKE '%http%'"""
        )


def downgrade() -> None:
    # Concurrently here too: a plain DROP INDEX takes ACCESS EXCLUSIVE on
    # messages, which is the stronger of the two locks this migration avoids.
    with op.get_context().autocommit_block():
        op.execute("DROP INDEX CONCURRENTLY IF EXISTS ix_messages_links")
