"""indexes for the preview tools' keyset walks

Revision ID: a4f81c6b2e07
Revises: b7e21c4a9d33
Create Date: 2026-09-09 11:20:00.000000

Hand-written, not autogenerated: two of these carry the tools' own scan
predicates rather than a schema property, so the models do not describe them.

Batch 55 changed app/tools/backfill_pdf_previews.py and regenerate_previews.py
from reading their whole selection with `.all()` to walking it keyset-paged. That
bounded Python memory and, on its own, would have traded it for database work:
neither message_attachments nor uploads had ANY index on created_at — only the
primary key and message_attachments' FK index on message_id — so every
continuation query had to filter and sort the remaining matching rows. Paging a
large table without a supporting index is the worse deal of the two.

Three indexes, because the two tools ask different questions:

  ix_message_attachments_created_keyset  (created_at, id)
      For regenerate_previews. Its --kind all selection is
      `mime_type LIKE 'image/%' OR mime_type = 'application/pdf'`, which no
      partial index can serve, so this is the general ordered access the keyset
      needs. Costs a real index entry on every attachment insert, which is the
      price of the walk being ordered at all.

  ix_message_attachments_pdf_unpreviewed  (created_at, id)
      WHERE mime_type = 'application/pdf' AND page_count IS NULL
      For backfill_pdf_previews' attachments pass. The general index above would
      also give it ordering, but its predicate is highly selective — almost every
      attachment already has a page_count — so walking the general index would
      touch a great many non-matching rows to fill one page. Being partial makes
      this nearly free to maintain: only unpreviewed PDFs get an entry at all.

  ix_uploads_pdf_unpreviewed  (created_at, id)
      WHERE mime_type = 'application/pdf' AND page_count IS NULL AND claimed = false
      For the uploads pass, which had no alternative index whatsoever. Same
      reasoning, and the selection is smaller again.

The two predicates must stay identical to the queries in the tools or Postgres
silently stops using the index — the same trade the links-tab partial index
records in 4471a6d661d3.
"""

from alembic import op

revision = "a4f81c6b2e07"
down_revision = "b7e21c4a9d33"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE INDEX ix_message_attachments_created_keyset ON message_attachments (created_at, id)")
    op.execute(
        """CREATE INDEX ix_message_attachments_pdf_unpreviewed
           ON message_attachments (created_at, id)
           WHERE mime_type = 'application/pdf' AND page_count IS NULL"""
    )
    op.execute(
        """CREATE INDEX ix_uploads_pdf_unpreviewed
           ON uploads (created_at, id)
           WHERE mime_type = 'application/pdf' AND page_count IS NULL AND claimed = false"""
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_uploads_pdf_unpreviewed")
    op.execute("DROP INDEX IF EXISTS ix_message_attachments_pdf_unpreviewed")
    op.execute("DROP INDEX IF EXISTS ix_message_attachments_created_keyset")
